language: android 
android: 
    components: 
        - build-tools-21.1.2
        - android-21
before_script:
    - chmod +x gradlew
script:
    - ./gradlew :library:check
after_success:
    - ./gradlew jacocoTestReport coveralls